name: Publish

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: read
  checks: read
  packages: write
  statuses: write

jobs:
  publish-ghp:
    name: Publish Gem to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"
          bundler-cache: true
      - run: bundle install
      - shell: bash
        run: |
          set +x
          mkdir -p ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :github: Bearer ${{ secrets.GITHUB_TOKEN }}
          :rubygems: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF

          chmod 0600 ~/.gem/credentials
          set -x

          bundle exec gem build *.gemspec
          bundle exec gem push *.gem --key github --host "https://rubygems.pkg.github.com/chtzvt"
          # bundle exec gem push *.gem --key rubygems --host "https://rubygems.org" - Need to work out OTP codes